### ISSUE TITLE
Update DPPI after iPRES 2024

### ISSUE THREAD

**Issue by anjackson** [digipres/publications#17]
Update this page: https://www.digipres.org/publications/ipres/ipres-2024/

This includes:

- Adding useful links, e.g. collaborative notes, blog posts from iPRES 2024
- Importing the publications data when it becomes available.
- Links to session recordings, when they become available.

You can propose changes directly using this link: [Edit via CMS (requires GitHub login)](https://digipres-org-publications.netlify.app/admin/#/collections/ipres-conferences/entries/ipres-2024/index) and that will open a PR for me to review.

Or edit the page here: https://github.com/digipres/publications/blob/main/ipres/ipres-2024/index.md

Or just comment below or ping me things on https://digipres.club/@anj or any other route to me or the DPC!

**Comment by amanda-tome** [comment]
Hi Andy, It seems the iPres 2024 posters are located at a different [Zenodo link](https://zenodo.org/communities/ipres2024posters/records?q=&l=list&p=1&s=10&sort=newest).

**Comment by anjackson** [comment]
Added, thank you @amanda-tome !

**Comment by anjackson** [comment]
I'm closing this as I can just pick up any future additions as we go.
